# Generated by Django 4.1.7 on 2023-03-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_collection_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['customer__last_name', 'customer__first_name', 'placed_at']},
        ),
    ]
