# Generated by Django 4.1.7 on 2023-03-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_customer_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
    ]
