# Generated by Django 4.1.7 on 2023-03-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_customer_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
