# Generated by Django 4.1.7 on 2023-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_image_alter_productimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default=1, upload_to='store/icons/'),
            preserve_default=False,
        ),
    ]
