# Generated by Django 4.1.7 on 2023-03-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_subcollection_product_subcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcollection',
        ),
        migrations.DeleteModel(
            name='SubCollection',
        ),
    ]
